FROM python:3.6-slim

COPY . .

RUN apt-get update && apt-get install -y --no-install-recommends \
    python3 \
    python3-pip \
    vim 
 
RUN pip3 install -r ./requirements.txt

EXPOSE 5000

CMD ["uvicorn", "main:app","--host", "0.0.0.0", "--port", "5000"]
